import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Linking,
  Share,
  ActivityIndicator,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Card } from '../ui/Card';
import { useI18n } from '../../lib/i18n';
import {
  useFinalSignedPdfUrl,
  useSignedContractDocuments,
  type Contract,
  type SignedContractDocument,
} from '../../lib/api/contracts';
import {
  colors,
  spacing,
  fontSize,
  fontWeight,
  borderRadius,
} from '../../constants/theme';

interface FinalSignedContractCardProps {
  contract: Pick<
    Contract,
    'final_pdf_url' | 'final_pdf_storage_path' | 'property_id' | 'property'
  >;
}

/**
 * Renders the auto-generated signed contract PDF (written by the backend
 * after the remote signing snapshot completes). Falls back to scanning the
 * linked property's `property_documents` for `signed_contract` rows when
 * the contract row itself doesn't carry a final PDF URL.
 *
 * Distinct from `SignedPdfUpload`, which is the broker's manual upload of
 * a paper-signed copy.
 */
export function FinalSignedContractCard({ contract }: FinalSignedContractCardProps) {
  const { t, formatDate } = useI18n();

  const { data: directUrl, isLoading: loadingDirect } = useFinalSignedPdfUrl(contract);

  const propertyId = contract.property_id ?? contract.property?.id ?? null;
  const hasContractFinal = !!contract.final_pdf_url || !!contract.final_pdf_storage_path;
  const { data: propertyDocs = [], isLoading: loadingDocs } = useSignedContractDocuments(
    hasContractFinal ? null : propertyId,
  );

  const isLoading = loadingDirect || loadingDocs;
  const hasDirect = !!directUrl;
  const hasPropertyDocs = !hasContractFinal && propertyDocs.length > 0;

  if (!hasDirect && !hasPropertyDocs && !isLoading) return null;

  const handleOpen = (url: string) => {
    Linking.openURL(url);
  };

  const handleShare = async (url: string) => {
    try {
      await Share.share({ url, message: url });
    } catch {
      /* user cancelled */
    }
  };

  return (
    <Card style={styles.card}>
      <View style={styles.headerRow}>
        <Text style={styles.title}>{t('finalContract_title')}</Text>
        <View style={styles.autoBadge}>
          <Ionicons name="sparkles-outline" size={12} color={colors.primary} />
          <Text style={styles.autoBadgeText}>{t('finalContract_autoGenerated')}</Text>
        </View>
      </View>

      <Text style={styles.subtitle}>{t('finalContract_subtitle')}</Text>

      {isLoading && !hasDirect && !hasPropertyDocs ? (
        <View style={styles.loadingRow}>
          <ActivityIndicator size="small" color={colors.primary} />
          <Text style={styles.loadingText}>{t('finalContract_loading')}</Text>
        </View>
      ) : null}

      {hasDirect && directUrl ? (
        <View style={styles.body}>
          <View style={styles.iconRow}>
            <View style={styles.successIcon}>
              <Ionicons name="checkmark-circle" size={24} color={colors.success} />
            </View>
            <Text style={styles.bodyText}>{t('finalContract_ready')}</Text>
          </View>
          <View style={styles.actions}>
            <TouchableOpacity style={styles.actionChip} onPress={() => handleOpen(directUrl)}>
              <Ionicons name="eye-outline" size={16} color={colors.primary} />
              <Text style={styles.actionChipText}>{t('finalContract_open')}</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.actionChip} onPress={() => handleShare(directUrl)}>
              <Ionicons name="share-outline" size={16} color={colors.primary} />
              <Text style={styles.actionChipText}>{t('finalContract_share')}</Text>
            </TouchableOpacity>
          </View>
        </View>
      ) : null}

      {hasPropertyDocs ? (
        <View style={styles.body}>
          {propertyDocs.map((doc) => (
            <PropertyDocRow
              key={doc.id}
              doc={doc}
              formatDate={formatDate}
              onOpen={handleOpen}
              onShare={handleShare}
              openLabel={t('finalContract_open')}
              shareLabel={t('finalContract_share')}
            />
          ))}
        </View>
      ) : null}
    </Card>
  );
}

function PropertyDocRow({
  doc,
  formatDate,
  onOpen,
  onShare,
  openLabel,
  shareLabel,
}: {
  doc: SignedContractDocument;
  formatDate: (date: string | Date, options?: Intl.DateTimeFormatOptions) => string;
  onOpen: (url: string) => void;
  onShare: (url: string) => void;
  openLabel: string;
  shareLabel: string;
}) {
  const url = doc.signed_url;
  return (
    <View style={styles.docRow}>
      <View style={styles.iconRow}>
        <View style={styles.successIcon}>
          <Ionicons name="document-text" size={20} color={colors.primary} />
        </View>
        <View style={styles.docMeta}>
          <Text style={styles.docName} numberOfLines={1}>
            {doc.file_name}
          </Text>
          <Text style={styles.docDate}>
            {formatDate(doc.created_at, { day: '2-digit', month: 'short', year: 'numeric' })}
          </Text>
        </View>
      </View>
      {url ? (
        <View style={styles.actions}>
          <TouchableOpacity style={styles.actionChip} onPress={() => onOpen(url)}>
            <Ionicons name="eye-outline" size={16} color={colors.primary} />
            <Text style={styles.actionChipText}>{openLabel}</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.actionChip} onPress={() => onShare(url)}>
            <Ionicons name="share-outline" size={16} color={colors.primary} />
            <Text style={styles.actionChipText}>{shareLabel}</Text>
          </TouchableOpacity>
        </View>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.success + '40',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
    gap: spacing.sm,
  },
  title: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.semibold,
    color: colors.text,
    flex: 1,
  },
  autoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary + '12',
    paddingVertical: 2,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.sm,
  },
  autoBadgeText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    color: colors.primary,
  },
  subtitle: {
    fontSize: fontSize.xs,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  body: {
    gap: spacing.sm,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  loadingText: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  successIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.success + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bodyText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: colors.text,
    flex: 1,
  },
  actions: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  actionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.primary + '10',
    borderRadius: borderRadius.sm,
  },
  actionChipText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    color: colors.primary,
  },
  docRow: {
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  docMeta: {
    flex: 1,
  },
  docName: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: colors.text,
  },
  docDate: {
    fontSize: fontSize.xs,
    color: colors.textSecondary,
    marginTop: 1,
  },
});
